name: learn-env
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy-base=1.23.1
  - pandas=1.1.3
  - seaborn=0.11.0
  - matplotlib=3.3.1
  - scipy=1.9.0
  - sklearn=0.23.2
  - imblearn=0.7.0
